In [2]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-01 17:51:54--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.1s

2024-10-01 17:51:55 (2.12 MB/s) - 'laptops.csv' saved [298573/298573]

In [47]:
import pandas as pd 
import numpy as np

Q1. Pandas version

What's the version of Pandas that you installed?

In [29]:
pd.__version__

'2.2.2'

In [5]:
df = pd.read_csv("/kaggle/working/laptops.csv")

In [7]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

Q2. Records count

How many records are in the dataset?

In [30]:
len(df)

2160

Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [31]:
brands = df['Brand'].unique().tolist()

In [32]:
brands

['Asus',
 'Alurin',
 'MSI',
 'HP',
 'Lenovo',
 'Medion',
 'Acer',
 'Apple',
 'Razer',
 'Gigabyte',
 'Dell',
 'LG',
 'Samsung',
 'PcCom',
 'Microsoft',
 'Primux',
 'Prixton',
 'Dynabook Toshiba',
 'Thomson',
 'Denver',
 'Deep Gaming',
 'Vant',
 'Innjoo',
 'Jetwing',
 'Millenium',
 'Realme',
 'Toshiba']

In [14]:
len(brands)

27

Q4. Missing values

How many columns in the dataset have missing values?

In [16]:
# How many columns in the dataset have missing values
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5 . What's the maximum final price of Dell notebooks in the dataset?

In [19]:

dell_max_price = df[df['Brand'] == 'Dell']['Final Price'].max()

In [20]:
dell_max_price

3936.0

Q6. Median value of Screen

Find the median value of Screen column in the dataset.

Next, calculate the most frequent value of the same Screen column.

Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

Now, calculate the median value of Screen once again.

In [21]:
df['Screen'].median()

15.6

In [23]:
df['Screen'].mode()[0]

15.6

In [24]:
mode = df['Screen'].mode()[0]

In [27]:
df.fillna(mode , inplace = True)

In [28]:
df['Screen'].median()

15.6

Q7. Sum of weights

Select all the "Innjoo" laptops from the dataset.

Select only columns RAM, Storage, Screen.

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [40]:
new_df = df[df['Brand']=='Innjoo'][["RAM","Storage","Screen"]]

In [41]:
new_df

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [42]:
X = new_df.values

In [43]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [45]:
type(X)

numpy.ndarray

In [49]:
XTX = np.dot(X.T , X)

In [50]:
inverse = A_inverse = np.linalg.inv(XTX)

In [51]:
y = [1100, 1300, 800, 900, 1000, 1100]

 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [52]:
s1 = np.dot(inverse,X.T)
W = np.dot(s1 , y)

In [55]:
W.sum()

91.2998806299555

In [56]:
W.sum().round()

91.0